### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by unrealwill** [datamade/parserator#29] opened 2016-06-22 18:37 UTC
In a fresh virtualenv (here in python 3 but also bugs in python 2.7, on Ubuntu 14.04).
It crashed with the same error when I tried a project of my own. So I checked if usaddress work on my machine with 

>  git clone https://github.com/datamade/usaddress.git  
>  cd usaddress  
>  pip install -r requirements.txt  
>  python setup.py develop  
> parserator train training/labeled.xml usaddress 

Here is the result of the execution and stack trace : 

> ~/parsertest3/usaddress$ parserator train training/labeled.xml usaddress
> /home/darkblue/parsertest3/usaddress/usaddress/__init__.py:160: UserWarning: You must train the model (parserator train --trainfile FILES) to create the usaddr.crfsuite file before you can use the parse and tag methods
>   warnings.warn('You must train the model (parserator train --trainfile FILES) to create the %s file before you can use the parse and tag methods' %MODEL_FILE)
> 
> training model on 1046 training examples from ['training/labeled.xml']
> Traceback (most recent call last):
>   File "/home/darkblue/parsertest3/bin/parserator", line 11, in <module>
>     sys.exit(dispatch())
>   File "/home/darkblue/parsertest3/lib/python3.4/site-packages/parserator/main.py", line 54, in dispatch
>     args.func(args)
>   File "/home/darkblue/parsertest3/lib/python3.4/site-packages/parserator/main.py", line 81, in train
>     training.train(module, train_file_list, modelfile)
>   File "/home/darkblue/parsertest3/lib/python3.4/site-packages/parserator/training.py", line 96, in train
>     trainModel(training_data, module, model_file)
>   File "/home/darkblue/parsertest3/lib/python3.4/site-packages/parserator/training.py", line 33, in trainModel
>     trainer.train(model_path)
>   File "pycrfsuite/_pycrfsuite.pyx", line 359, in pycrfsuite._pycrfsuite.BaseTrainer.train (pycrfsuite/_pycrfsuite.cpp:3857)
>   File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string (pycrfsuite/_pycrfsuite.cpp:9777)
> TypeError: expected bytes, NoneType found

Can you advice ?
Thank you

**Comment by cathydeng** [comment] 2016-06-22 19:21
hey @unrealwill - thanks for reporting. if you need a solution sooner while we work on fixing this, try installing parserator version 0.4.1. I think 0.4.1 may have had python 3 compatibility issues, but definitely worked w/ python 2.

@fgregg I checked & confirmed that training is currently broken for both python 2 & python 3. I checked out my last commit & it worked then, so it looks like it was introduced in one of your recent changes. thoughts as to why? also, we should prob have tests for training...😝

**Comment by fgregg** [comment] 2016-06-22 19:42
sorry, don't have time to look at this right now

On Wed, Jun 22, 2016 at 2:21 PM, Cathy Deng <notifications@github.com>
wrote:

> hey @unrealwill <https://github.com/unrealwill> - thanks for reporting.
> if you need a solution sooner while we work on fixing this, try installing
> parserator version 0.4.1. I think 0.4.1 may have had python 3 compatibility
> issues, but definitely worked w/ python 2.
>
> @fgregg <https://github.com/fgregg> I checked & confirmed that training
> is currently broken for both python 2 & python 3. I checked out my last
> commit & it worked then, so it looks like it was introduced in one of your
> recent changes. thoughts as to why? also, we should prob have tests for
> training...😝
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/datamade/parserator/issues/29#issuecomment-227849532>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAgxbVCYZbeEjJtj7Ih2x-lpbkyMuHyRks5qOYs0gaJpZM4I8Frj>
> .
>



-- 
773.888.2718

**Comment by unrealwill** [comment] 2016-06-22 21:43
@cathydeng Thank you for confirming the bug, I was worrying I had made a noob mistake. I'll give 0.4.1 a try tomorrow.
 @fgregg No problem I'm not in a hurry.

**Comment by oliviac12** [comment] 2016-07-08 05:59
@cathydeng I also have the similar issue while doing train, I changed the version to 0.4.1 but still not working. I am using Anaconda, python 2.7.
This is the error I am getting

Traceback (most recent call last):
  File "/Users/qinnanchen/anaconda/bin/parserator", line 11, in <module>
    sys.exit(dispatch())
  File "/Users/qinnanchen/anaconda/lib/python2.7/site-packages/parserator/main.py", line 37, in dispatch
    args.func(args)
  File "/Users/qinnanchen/anaconda/lib/python2.7/site-packages/parserator/main.py", line 66, in train
    training.train(module, train_file_list)
  File "/Users/qinnanchen/anaconda/lib/python2.7/site-packages/parserator/training.py", line 88, in train
    model_path = module.__name__+'/'+module.MODEL_FILE
AttributeError: 'module' object has no attribute 'MODEL_FILE'


Thank you!

**Comment by cathydeng** [comment] 2016-07-08 17:19
hey @oliviac12 - what command did you run? did you include the module name when you tried to train?

**Comment by oliviac12** [comment] 2016-07-08 17:22
hey @cathydeng  Thanks for the quick response. Yes I was just doing the testing code in the probablypeople page. This is the command I ran 

`parserator train name_data/labeled/person_labeled.xml,name_data/labeled/company_labeled.xml probablepeople`

But then I read your comment earlier saying you confirmed train is broken right now, so I am in the middle of the process to go through the commit history to see if I can figure it out. If you can help that would be great!

**Comment by cathydeng** [comment] 2016-07-08 17:27
you can manually pip install parserator version 0.4.1 to avoid going back in the commit history - let me know if it still doesn't work w/ the older parserator version

**Comment by oliviac12** [comment] 2016-07-08 17:28
I tried parserator 0.4.1 last night actually and still getting the same error after read what you said before. But I will try again and let you know. thanks!

**Comment by oliviac12** [comment] 2016-07-08 17:30
Yup, still not working. 
`Olivias-MacBook-Air:probablepeople qinnanchen$ pip install parserator==0.4.1
Collecting parserator==0.4.1
Requirement already satisfied (use --upgrade to upgrade): future>=0.14.3 in /Users/qinnanchen/anaconda/lib/python2.7/site-packages (from parserator==0.4.1)
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.4.1 in /Users/qinnanchen/anaconda/lib/python2.7/site-packages (from parserator==0.4.1)
Requirement already satisfied (use --upgrade to upgrade): python-crfsuite>=0.7 in /Users/qinnanchen/anaconda/lib/python2.7/site-packages (from parserator==0.4.1)
Installing collected packages: parserator
Successfully installed parserator-0.4.1
Olivias-MacBook-Air:probablepeople qinnanchen$ parserator train name_data/labeled/person_labeled.xml,name_data/labeled/company_labeled.xml probablepeople
/Users/qinnanchen/probablepeople/probablepeople/__init__.py:64: UserWarning: You must train the model (parserator train [traindata] [modulename]) to create the generic_learned_settings.crfsuite file before you can use the parse and tag methods
  warnings.warn('You must train the model (parserator train [traindata] [modulename]) to create the %s file before you can use the parse and tag methods' % MODEL_FILES[model_type])
/Users/qinnanchen/probablepeople/probablepeople/__init__.py:64: UserWarning: You must train the model (parserator train [traindata] [modulename]) to create the person_learned_settings.crfsuite file before you can use the parse and tag methods
  warnings.warn('You must train the model (parserator train [traindata] [modulename]) to create the %s file before you can use the parse and tag methods' % MODEL_FILES[model_type])
/Users/qinnanchen/probablepeople/probablepeople/__init__.py:64: UserWarning: You must train the model (parserator train [traindata] [modulename]) to create the company_learned_settings.crfsuite file before you can use the parse and tag methods
  warnings.warn('You must train the model (parserator train [traindata] [modulename]) to create the %s file before you can use the parse and tag methods' % MODEL_FILES[model_type])
Traceback (most recent call last):
  File "/Users/qinnanchen/anaconda/bin/parserator", line 11, in <module>
    sys.exit(dispatch())
  File "/Users/qinnanchen/anaconda/lib/python2.7/site-packages/parserator/main.py", line 37, in dispatch
    args.func(args)
  File "/Users/qinnanchen/anaconda/lib/python2.7/site-packages/parserator/main.py", line 66, in train
    training.train(module, train_file_list)
  File "/Users/qinnanchen/anaconda/lib/python2.7/site-packages/parserator/training.py", line 88, in train
    model_path = module.__name__+'/'+module.MODEL_FILE
AttributeError: 'module' object has no attribute 'MODEL_FILE'`

**Comment by oliviac12** [comment] 2016-07-08 17:31
@cathydeng  doesn't seem like 0.4.1 works for me.

Olivias-MacBook-Air:probablepeople qinnanchen$ pip install parserator==0.4.1
Collecting parserator==0.4.1
Requirement already satisfied (use --upgrade to upgrade): future>=0.14.3 in /Users/qinnanchen/anaconda/lib/python2.7/site-packages (from parserator==0.4.1)
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.4.1 in /Users/qinnanchen/anaconda/lib/python2.7/site-packages (from parserator==0.4.1)
Requirement already satisfied (use --upgrade to upgrade): python-crfsuite>=0.7 in /Users/qinnanchen/anaconda/lib/python2.7/site-packages (from parserator==0.4.1)
Installing collected packages: parserator
Successfully installed parserator-0.4.1
Olivias-MacBook-Air:probablepeople qinnanchen$ parserator train name_data/labeled/person_labeled.xml,name_data/labeled/company_labeled.xml probablepeople
/Users/qinnanchen/probablepeople/probablepeople/__init__.py:64: UserWarning: You must train the model (parserator train [traindata] [modulename]) to create the generic_learned_settings.crfsuite file before you can use the parse and tag methods
  warnings.warn('You must train the model (parserator train [traindata] [modulename]) to create the %s file before you can use the parse and tag methods' % MODEL_FILES[model_type])
/Users/qinnanchen/probablepeople/probablepeople/__init__.py:64: UserWarning: You must train the model (parserator train [traindata] [modulename]) to create the person_learned_settings.crfsuite file before you can use the parse and tag methods
  warnings.warn('You must train the model (parserator train [traindata] [modulename]) to create the %s file before you can use the parse and tag methods' % MODEL_FILES[model_type])
/Users/qinnanchen/probablepeople/probablepeople/__init__.py:64: UserWarning: You must train the model (parserator train [traindata] [modulename]) to create the company_learned_settings.crfsuite file before you can use the parse and tag methods
  warnings.warn('You must train the model (parserator train [traindata] [modulename]) to create the %s file before you can use the parse and tag methods' % MODEL_FILES[model_type])
Traceback (most recent call last):
  File "/Users/qinnanchen/anaconda/bin/parserator", line 11, in <module>
    sys.exit(dispatch())
  File "/Users/qinnanchen/anaconda/lib/python2.7/site-packages/parserator/main.py", line 37, in dispatch
    args.func(args)
  File "/Users/qinnanchen/anaconda/lib/python2.7/site-packages/parserator/main.py", line 66, in train
    training.train(module, train_file_list)
  File "/Users/qinnanchen/anaconda/lib/python2.7/site-packages/parserator/training.py", line 88, in train
    model_path = module.__name__+'/'+module.MODEL_FILE
AttributeError: 'module' object has no attribute 'MODEL_FILE'

**Comment by cathydeng** [comment] 2016-07-08 17:45
ok so, looks like the most recent version of probablepeople needs the most recent version of parserator (due to some recent changes where you can have multiple models per module), which is broken. if you clone probablepeople at commit 6cb9f7ecc6d77496c580359cb63dd38ddfab3ae9, & use parserator v 0.4.1, it should work. sorry about this! will let you know when everything is fixed.

**Comment by oliviac12** [comment] 2016-07-08 17:55
can you please tell me how to clone probablepeople at a specific commit? sorry I am relatively new to git, I googled and found git reset --hard [commit number], is that the one I should use?  Thank you!

**Comment by cathydeng** [comment] 2016-07-08 18:00
yup that would work. and then after that, run `python setup.py develop` again

**Comment by oliviac12** [comment] 2016-07-08 18:22
@cathydeng  It worked! I already added and trained new data that I want. Thanks so much, you literally saved my day :)

**Comment by cathydeng** [comment] 2016-08-05 16:24
the train command is now fixed w/ parserator v0.6.0

(the probablepeople library had an additional issue, & training for that is fixed w/ v0.5.1 & parserator v0.6.0)

**Closed by cathydeng** 2016-08-05 16:24 UTC
